import { Experience, FleetUnit, Reservation, AddonService, UserAccount, AvailabilityBlock } from './types';

export const INITIAL_USER: UserAccount = {
  id: 'usr-bajaride-001',
  email: 'piloto.demo@bajaride.com',
  name: 'Alejandro Morales',
  phone: '+52 646 192 8841',
  emergencyContact: 'Sofía Morales (+52 646 555 1290)',
  driversLicense: 'BC-EXP-8839210',
  roles: ['CLIENTE', 'SOCIO', 'MASTER_ADMIN'],
  activeMode: 'CLIENTE',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
  socioProfile: {
    businessName: 'Desert Kings Baja Outfitters S.A. de C.V.',
    scoreCertified: true,
    satRfc: 'DKB190412R82',
    clabeInterbancaria: '012 180 00492819382 1',
    bankName: 'BBVA México',
  },
};

export const DEMO_ADDONS: AddonService[] = [
  {
    id: 'addon-gopro',
    name: 'Pack Video 4K GoPro HERO 12',
    description: 'Montaje en roll cage con memoria SD 64GB de regalo',
    priceUSD: 45,
    iconName: 'Camera',
  },
  {
    id: 'addon-suit',
    name: 'Traje Nomex & Casco con Intercom Air',
    description: 'Equipamiento profesional de ventilación forzada',
    priceUSD: 30,
    iconName: 'Shield',
  },
  {
    id: 'addon-bbq',
    name: 'Almuerzo Campestre & Asado de Arrachera',
    description: 'Comida en campamento base en el desierto con bebidas no alcohólicas',
    priceUSD: 35,
    iconName: 'Utensils',
  },
];

export const DEMO_EXPERIENCES: Experience[] = [
  {
    id: 'exp-sf-dunes',
    title: 'Desafío Dunas Blancas de San Felipe',
    shortDescription: 'Crestas gigantes, arena suave y aceleración a fondo junto al Mar de Cortés.',
    fullDescription: 'Travesía intensa en las formaciones de dunas más icónicas del norte de Baja California. Conducirás unidades Can-Am Maverick X3 preparadas con llantas de paleta sobre las crestas del desierto de San Felipe, finalizando en la costa con vistas privilegiadas.',
    category: 'UTV / Side-by-Side',
    difficulty: 'Intermedio',
    durationHours: 3.5,
    priceUSD: 280,
    socioId: 'socio-dk-01',
    socioName: 'Desert Kings Baja Outfitters',
    socioRating: 4.95,
    socioReviewsCount: 142,
    socioVerified: true,
    heroImage: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=1200&auto=format&fit=crop&q=80',
    ],
    locationName: 'San Felipe, B.C.',
    coordinates: {
      lat: 31.0289,
      lng: -114.8344,
      label: 'Campamento Base Dunas Norte',
      reference: 'Km 12 Carretera San Felipe - Puertecitos',
      vhfChannel: '146.520 MHz (Ch 2)',
      zone: 'San Felipe',
    },
    whatsIncluded: [
      'UTV Can-Am Turbo 2024 asegurado',
      'Casco Snell/DOT con radio comunicación',
      'Combustible VP Racing para toda la ruta',
      'Guía líder certificado SCORE International',
      'Agua embotellada y snacks energéticos',
    ],
    requiredGear: [
      'Licencia de conducir vigente (+18 años)',
      'Calzado cerrado resistente (botas o tenis)',
      'Pantalón largo y lentes antipolvo',
    ],
    maxVehiclesPerGroup: 4,
    isActive: true,
    featured: true,
  },
  {
    id: 'exp-ojos-negros',
    title: 'Ruta de la Leyenda: Ojos Negros a Valle de la Trinidad',
    shortDescription: 'Tierra compacta, whoops de la Baja 500 y cañones técnicos en la Sierra de Juárez.',
    fullDescription: 'Experimenta la adrenalina pura transitando por tramos legendarios utilizados en las carreras Baja 1000 y 500. Senderos empedrados, cruces secos de arroyos y curvas peraltadas en terrenos de alta velocidad.',
    category: 'Trophy Truck Demo',
    difficulty: 'Avanzado',
    durationHours: 5,
    priceUSD: 490,
    socioId: 'socio-dk-01',
    socioName: 'Desert Kings Baja Outfitters',
    socioRating: 4.98,
    socioReviewsCount: 89,
    socioVerified: true,
    heroImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&auto=format&fit=crop&q=80',
    ],
    locationName: 'Ojos Negros, B.C.',
    coordinates: {
      lat: 31.8542,
      lng: -116.2711,
      label: 'Base Camp Rancho Nelson',
      reference: 'Km 38 Carretera Ensenada - San Felipe',
      vhfChannel: '151.625 MHz (Ch 5 Weatherman)',
      zone: 'Ojos Negros',
    },
    whatsIncluded: [
      'Vehículo Trophy Lite / Spec Truck adaptado',
      'Overol contra fuego y HANS device',
      'Teléfono satelital Garmin inReach en cada unidad',
      'Mecánico de soporte en vehículo nodriza',
      'Comida asada tradicional al término',
    ],
    requiredGear: [
      'Experiencia previa en manejo off-road',
      'Licencia física vigente',
      'Firma de deslinde de responsabilidad',
    ],
    maxVehiclesPerGroup: 3,
    isActive: true,
    featured: true,
  },
  {
    id: 'exp-ensenada-coastal',
    title: 'Acantilados del Pacífico y Bahía Soledad',
    shortDescription: 'Paisajes oceánicos, senderos salinos y miradores rocosos al atardecer.',
    fullDescription: 'Recorrido escénico sobre la cordillera costera de Ensenada. Ideal para quienes buscan combinar la adrenalina de los senderos todoterreno con vistas panorámicas inolvidables del Océano Pacífico.',
    category: 'ATV / Cuatrimoto',
    difficulty: 'Principiante',
    durationHours: 2.5,
    priceUSD: 160,
    socioId: 'socio-coastal-02',
    socioName: 'Baja Coast Adventures',
    socioRating: 4.88,
    socioReviewsCount: 215,
    socioVerified: true,
    heroImage: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=1200&auto=format&fit=crop&q=80',
    ],
    locationName: 'Ensenada, B.C.',
    coordinates: {
      lat: 31.7822,
      lng: -116.6321,
      label: 'Punto La Bufadora Offroad Track',
      reference: 'Entrada Ejido Esteban Cantú',
      vhfChannel: '146.520 MHz',
      zone: 'Ensenada',
    },
    whatsIncluded: [
      'ATV Honda TRX 420cc automático',
      'Casco protector con visera antipolvo',
      'Chaleco de alta visibilidad',
      'Fotografías digitales del recorrido',
    ],
    requiredGear: [
      'Ropa que se pueda empolvar',
      'Identificación oficial',
    ],
    maxVehiclesPerGroup: 6,
    isActive: true,
    featured: false,
  },
];

export const DEMO_FLEET: FleetUnit[] = [
  {
    id: 'unit-canam-01',
    name: 'Can-Am Maverick X3 Turbo RR #01',
    model: '2024 Rotax ACE 200HP',
    plateNumber: 'BC-OFF-901',
    status: 'DISPONIBLE',
    hoursRun: 184,
    nextServiceHours: 200,
    lastInspectionDate: '2026-09-18',
    assignedDriver: 'Carlos Vega',
  },
  {
    id: 'unit-canam-02',
    name: 'Can-Am Maverick X3 Turbo RR #02',
    model: '2024 Rotax ACE 200HP',
    plateNumber: 'BC-OFF-902',
    status: 'EN_RUTA',
    hoursRun: 198,
    nextServiceHours: 200,
    lastInspectionDate: '2026-09-20',
    assignedDriver: 'Mario Beltrán',
  },
  {
    id: 'unit-trophy-03',
    name: 'Baja Bug 2.4L Ecotec #03',
    model: '2023 Desert Race Chassis',
    plateNumber: 'BC-RACE-044',
    status: 'MANTENIMIENTO',
    hoursRun: 320,
    nextServiceHours: 300,
    lastInspectionDate: '2026-09-15',
  },
];

export const DEMO_RESERVATIONS: Reservation[] = [
  {
    id: 'BR-84920',
    experienceId: 'exp-sf-dunes',
    experienceTitle: 'Desafío Dunas Blancas de San Felipe',
    experienceImage: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&auto=format&fit=crop&q=80',
    category: 'UTV / Side-by-Side',
    socioId: 'socio-dk-01',
    socioName: 'Desert Kings Baja Outfitters',
    date: '2026-09-25',
    timeSlot: '08:30 AM',
    vehiclesCount: 1,
    participantsCount: 2,
    selectedAddons: [DEMO_ADDONS[0]],
    totalPriceUSD: 325,
    customerName: 'Alejandro Morales',
    customerEmail: 'piloto.demo@bajaride.com',
    customerPhone: '+52 646 192 8841',
    emergencyContact: 'Sofía Morales (+52 646 555 1290)',
    driversLicense: 'BC-EXP-8839210',
    state: 'CONFIRMADA',
    createdAt: '2026-09-20T10:15:00Z',
    meetingPoint: DEMO_EXPERIENCES[0].coordinates,
    assignedFleetUnitId: 'unit-canam-01',
    assignedGuideName: 'Carlos Vega (Líder)',
    checkInPassed: false,
  },
  {
    id: 'BR-49281',
    experienceId: 'exp-ojos-negros',
    experienceTitle: 'Ruta de la Leyenda: Ojos Negros a Valle de la Trinidad',
    experienceImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80',
    category: 'Trophy Truck Demo',
    socioId: 'socio-dk-01',
    socioName: 'Desert Kings Baja Outfitters',
    date: '2026-09-23',
    timeSlot: '01:30 PM',
    vehiclesCount: 1,
    participantsCount: 2,
    selectedAddons: [DEMO_ADDONS[1], DEMO_ADDONS[2]],
    totalPriceUSD: 555,
    customerName: 'Roberto Fuentes',
    customerEmail: 'roberto.fuentes@motorsport.mx',
    customerPhone: '+52 664 882 1099',
    emergencyContact: 'Raúl Fuentes (+52 664 123 4567)',
    driversLicense: 'SON-992182-A',
    state: 'ACTIVA',
    createdAt: '2026-09-18T14:30:00Z',
    meetingPoint: DEMO_EXPERIENCES[1].coordinates,
    assignedFleetUnitId: 'unit-canam-02',
    assignedGuideName: 'Mario Beltrán',
    checkInPassed: true,
  },
  {
    id: 'BR-19034',
    experienceId: 'exp-sf-dunes',
    experienceTitle: 'Desafío Dunas Blancas de San Felipe',
    experienceImage: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=1200&auto=format&fit=crop&q=80',
    category: 'UTV / Side-by-Side',
    socioId: 'socio-dk-01',
    socioName: 'Desert Kings Baja Outfitters',
    date: '2026-09-14',
    timeSlot: '05:00 PM',
    vehiclesCount: 2,
    participantsCount: 4,
    selectedAddons: [],
    totalPriceUSD: 560,
    customerName: 'Esteban Domínguez',
    customerEmail: 'esteban.d@gmail.com',
    customerPhone: '+52 686 554 9012',
    emergencyContact: 'Lucía Domínguez',
    driversLicense: 'BC-DL-77382',
    state: 'COMPLETADA',
    createdAt: '2026-09-10T09:00:00Z',
    meetingPoint: DEMO_EXPERIENCES[0].coordinates,
    checkInPassed: true,
  },
];

export const DEMO_AVAILABILITY_BLOCKS: AvailabilityBlock[] = [
  {
    id: 'block-01',
    experienceId: 'exp-sf-dunes',
    startDate: '2026-09-28',
    endDate: '2026-09-29',
    reason: 'Mantenimiento',
    notes: 'Revisión mayor de bandas CVT y amortiguadores FOX',
    createdAt: '2026-09-19T10:00:00Z',
  },
];
